<?php

namespace app\models;

use dektrium\user\models\User as BaseUser;
use Yii;

/**
 * User ActiveRecord model.
 * @property string $acl
 * @property integer $affected_to
 */
class User extends BaseUser
{
//    public $first_name;
//    public $last_name;
//    const VIP_ACCESS      = 1;
//    const ALL_REGIONS     = 2;
//    const ALTER_CLIENT    = 4;
//    const ALTER_PARTNER   = 8;
//    public $vip_access    = false;
//    public $all_regions   = false;
//    public $alter_client  = false;
//    public $alter_partner = false;
//    protected $_client;

    /**
     * User constructor.
     */
//    public function __construct($config = [])
//    {
//        $this->on(self::AFTER_REGISTER,function (){
//            $auth = Yii::$app->authManager;
//            $authorRole = $auth->getRole('customer');
//            $auth->assign($authorRole, $this->getId());
//        });
//        parent::__construct($config);
//    }
    public function getIsAdmin()
    {

        return parent::getIsAdmin() or array_key_exists('administrator', Yii::$app->authManager->getRolesByUser($this->id));
    }

//    public function scenarios()
//    {
//        $scenarios = parent::scenarios();
//        // add field to scenarios
//        $scenarios['register'][] = 'first_name';
//        $scenarios['register'][] = 'last_name';
//        $scenarios['create'][] = 'vip_access';
//        $scenarios['create'][] = 'affected_to';
//        $scenarios['create'][] = 'all_regions';
//        $scenarios['create'][] = 'alter_client';
//        $scenarios['create'][] = 'alter_partner';
//        $scenarios['update'][] = 'vip_access';
//        $scenarios['update'][] = 'affected_to';
//        $scenarios['update'][] = 'all_regions';
//        $scenarios['update'][] = 'alter_client';
//        $scenarios['update'][] = 'alter_partner';
//        return $scenarios;
//    }

//    public function afterFind()
//    {
//        parent::afterFind();
//        $this->vip_access    = ($this->acl & self::VIP_ACCESS)    == self::VIP_ACCESS;
//        $this->all_regions   = ($this->acl & self::ALL_REGIONS)   == self::ALL_REGIONS;
//        $this->alter_client  = ($this->acl & self::ALTER_CLIENT)  == self::ALTER_CLIENT;
//        $this->alter_partner = ($this->acl & self::ALTER_PARTNER) == self::ALTER_PARTNER;
//    }

//    public function beforeSave($insert)
//    {
//        $acl = 0;
//        if ($this->vip_access) $acl    |= self::VIP_ACCESS;
//        if ($this->all_regions) $acl   |= self::ALL_REGIONS;
//        if ($this->alter_client) $acl  |= self::ALTER_CLIENT;
//        if ($this->alter_partner) $acl |= self::ALTER_PARTNER;
//        $this->acl = $acl;
//        return parent::beforeSave($insert);
//    }

    /**
     * @inheritdoc
     */
//    public function rules()
//    {
//        $rule=parent::rules();
//        $rule[]= [['viewentreprise'], 'boolean'];
//        return $rule;
//    }

//    public function attributeLabels()
//    {
//        $attributeLabels = parent::attributeLabels();
//        $attributeLabels['viewentreprise'] = Yii::t('app','View Entreprise');
////        $attributeLabels['vip_access'] = Yii::t('app','vip_access');
////        $attributeLabels['all_regions'] = Yii::t('app','all_regions');
////        $attributeLabels['alter_client'] = Yii::t('app','alter_client');
////        $attributeLabels['alter_partner'] = Yii::t('app','alter_partner');
//        return $attributeLabels; // TODO: Change the autogenerated stub
//    }

//    public function hasVipAccess()
//    {
//        return $this->vip_access;
//    }

//    public function rules()
//    {
//        $rules = parent::rules();
//        // add some rules
//        $rules['fields'] = [['vip_access', 'all_regions', 'alter_client', 'alter_partner'], 'boolean'];
//        $rules[]  = [['first_name','last_name'], 'string', 'min' => 3, 'max' => 255];
//        $rules['affectation_country'] = [['affected_to'], 'integer'];
//        return $rules;
//    }

//    public function hasAllRegionsAccess()
//    {
//        return $this->all_regions;
//    }

//    public function setClientModel($client)
//    {
//        $this->_client =$client;
//    }

//    public function hasAlterClient()
//    {
//        return $this->alter_client;
//    }

//    public function hasAlterPartner()
//    {
//        return $this->alter_partner;
//    }

//    public function getOrders()
//    {
//        return $this->hasMany(Order::className(),['id_user'=>'id']);
//    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntreprises()
    {
        return $this->hasMany(Entreprise::className(), ['user_id' => 'id']);
    }


    /** @inheritdoc */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if ($insert) {
            $auth = Yii::$app->authManager;
            $authorRole = $auth->getRole('entreprise');
            $auth->assign($authorRole, $this->getId());
        }
    }
    public static function findByRole($role)
    {
        return static::find()
            ->join('LEFT JOIN','auth_assignment','auth_assignment.user_id = id')
            ->where(['auth_assignment.item_name' => $role])
            ->all();
    }
}
